version: '3.8'

services:
  nuxt-app:
    build:
      context: ./NuxtApp
    container_name: nuxt-app
    ports:
      - '3000:3000'
    env_file:
      - ./NuxtApp/.env # Load Nuxt-specific environment variables
    volumes:
      - ./NuxtApp:/app
    command: ["node", "/app/docker-script.js"] # Commande pour exécuter le script JS
    networks:
      - app-network

  strapi:
    build:
      context: ./Strapi
    container_name: strapi
    ports:
      - '1337:1337'
    env_file:
      - ./Strapi/.env # Load Strapi-specific environment variables
    volumes:
      - ./Strapi:/app              # Mount Strapi-specific project directory
    command: sh -c "npm install && npm run develop" # Install dependencies on start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
